# docker-compose.yml
services:
  web-consumer:
    build:
      context: .
      args:
        - DEV=true
    # The command is updated to run the consumer-api project
    command: gunicorn consumer-api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      # Mount the whole project directory to the container
      - .:/app
    environment:
      # Django에게 settings 파일의 위치를 알려줌
      - DJANGO_SETTINGS_MODULE=settings
      # 파이썬에게 최상위 모듈 경로를 알려줌
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy


  web-owner:
    build:
      context: .
      args:
        - DEV=true
    # A new service for the owner-api
    command: gunicorn owner-api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=settings
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  web-backoffice:
    build:
      context: .
      args:
        - DEV=true
    # A new service for the backoffice-api
    command: gunicorn backoffice-api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=settings
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  web-admin:
    build:
      context: .
      args:
        - DEV=true
    working_dir: /app/admin-api
    # A new service for the admin-api
    command: gunicorn admin-api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=settings
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    volumes:
      # Mount your Nginx configuration file
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    ports:
      - "80:80"
    depends_on:
      - web-consumer
      - web-owner
      - web-backoffice
      - web-admin

volumes:
  postgres_data: