# Generated by Django 5.0.7 on 2025-08-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('consumer', 'consumer'), ('owner', 'owner'), ('operator', 'operator')], default='consumer', max_length=20, verbose_name='사용자 유형'),
        ),
    ]
