# nginx/default.conf
upstream consumer_api {
    server web-consumer:8000;
}

upstream owner_api {
    server web-owner:8000;
}

upstream backoffice_api {
    server web-backoffice:8000;
}

server {
    listen 80;

    # 정적 파일 서빙을 위한 location 추가
    location /static/ {
        root /app;
    }

    # 미디어 파일 서빙을 위한 location 추가
    location /media/ {
        alias /app/media/; # Django의 MEDIA_ROOT 경로를 지정
    }

    # Route consumer-related requests
    location /api/consumer/ {
        proxy_pass http://consumer_api/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Route owner-related requests
    location /api/owner/ {
        proxy_pass http://owner_api/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Route backoffice-related requests
    location /api/backoffice/ {
        proxy_pass http://backoffice_api/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/ {
        proxy_pass http://backoffice_api;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}