# nginx/default.conf
upstream consumer_api {
    server web-consumer:8000;
}

upstream owner_api {
    server web-owner:8000;
}

server {
    listen 80;

    # Route consumer-related requests
    location /api/consumer/ {
        proxy_pass http://consumer_api/;
        proxy_set_header Host $host;
    }

    # Route owner-related requests
    location /api/owner/ {
        proxy_pass http://owner_api/;
        proxy_set_header Host $host;
    }
}